FROM ubuntu:16.04

LABEL maintainer=gurvsin3@in.ibm.com

ENV BUILD_VERSION="V1"

USER root
ENV DEBIAN_FRONTEND noninteractive
ENV USER_UID 1000
ENV USER_GID 1000
ENV DOCKER_GID 999

# Setup and install base system software
RUN echo "locales locales/locales_to_be_generated multiselect en_US.UTF-8 UTF-8" | debconf-set-selections \
    && echo "locales locales/default_environment_locale select en_US.UTF-8" | debconf-set-selections \
    && apt-get update \
    && rm -rf /var/lib/apt/lists/*
ENV LANG en_US.UTF-8

# bring system up-to-date
RUN apt-get update -qq && \
    apt-get upgrade -qqy

# Below dependencies required for OpenCV 
RUN apt-get install -y libsm6 libxext6 libxrender-dev
RUN apt-get install -y tesseract-ocr --fix-missing
RUN apt-get install -y software-properties-common 
RUN apt-get install -y python-software-properties
RUN apt-get clean && rm -rf /tmp/* /var/tmp/*

RUN add-apt-repository ppa:jonathonf/python-3.5
RUN apt-get update

RUN apt-get install -y libpq-dev build-essential python3.5 python3.5-dev python3-pip python3.5-venv

# Install Other dependencies
RUN apt-get update \
    && apt-get --yes --no-install-recommends install \
        wget bzip2 git make zlib \
    && rm -rf /var/lib/apt/lists/*

# update pip
RUN python3.5 -m pip install pip --upgrade
RUN python3.5 -m pip install wheel

RUN apt-get update

# Install Python modules
ADD requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt \
     && rm -rf ~/.cache/pip 

# Create a directory where our app will be placed
RUN mkdir -p /usr/src/app

#Change directory so that our commands run inside this new directory
WORKDIR /usr/src/app

COPY . .

RUN chmod 755 entrypoint.sh
RUN chmod 755 build.sh

RUN ./build.sh

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
CMD ["/bin/bash"]

# EXPOSE 80 8081
